

-- Delete existing schema if needed
DROP SCHEMA IF EXISTS quiz_app CASCADE;

CREATE SCHEMA IF NOT EXISTS quiz_app;



CREATE TABLE IF NOT EXISTS quiz_app.quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,             
  data JSONB NOT NULL,                            
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX IF NOT EXISTS idx_quizzes_created_at
ON quiz_app.quizzes (created_at DESC);
